выполняет задание Нужно больше функций(2)
htmlacademy-javascript/2062283-kekstagram-simple-27 pull request #3
Opened 2022-10-03 10:35 UTC by grechah

2022-10-03 14:33 UTC, Espanol-nikkol requested changes

2022-10-03 14:33 UTC, Espanol-nikkol commented on index.html
> +  <link rel=""
мусор?

2022-10-03 14:33 UTC, Espanol-nikkol commented on js/main.js
> +function getMaxCommentLength (lineLength, maxLength) {
название не корректное
Это не get
посмотри в руководстве, в конфе кинул

2022-10-04 07:52 UTC, grechah commented on index.html
> +  <link rel=""
убрал

2022-10-04 07:52 UTC, grechah commented on js/main.js
> +function getMaxCommentLength (lineLength, maxLength) {
поправил

2022-10-07 02:16 UTC, merged