Модуляция
htmlacademy-javascript/2062283-kekstagram-simple-27 pull request #5
Opened 2022-10-21 02:40 UTC by grechah

---
:mortar_board: [Модуляция](https://up.htmlacademy.ru/javascript/27/user/2062283/tasks/10)

2022-10-21 23:02 UTC, Espanol-nikkol commented
js файлы должны жить в папке js

2022-10-24 22:21 UTC, Espanol-nikkol requested changes

2022-10-24 22:21 UTC, Espanol-nikkol commented on util.js
> +export {getRandomElementOfArray};
давай писать экспорт сразу в строке, где объявляем переменную

2022-10-24 22:21 UTC, Espanol-nikkol commented on util.js
> +const getRandomElementOfArray = (someArray) => someArray[getRandomIntInclusive(0, someArray.length - 1)];
типа export const ...

2022-10-25 13:25 UTC, grechah commented on util.js
> +export {getRandomElementOfArray};
сделано

2022-10-25 13:25 UTC, grechah commented on util.js
> +const getRandomElementOfArray = (someArray) => someArray[getRandomIntInclusive(0, someArray.length - 1)];
сделано

2022-10-27 23:21 UTC, merged